name: Deploy Workflows using Databricks Assets Bundle (DAB) to Dev environment

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.py"

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - name: Configure Databricks
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        run: databricks configure

      - name: Validate DAB data resources
        run: databricks bundle validate

      - name: databricks bundle deploy to dev environment
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
        run: databricks bundle deploy
      
      - name: Run databricks job "my-job"
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          JOB_NAME: 'dab_demo_job'
        #  WAIT_TIMEOUT: '20m0s'
        run: |
          JOB_ID=$(databricks jobs list | grep -w $JOB_NAME | awk -F ' ' '{print $1}')
          databricks jobs run-now $JOB_ID 
        #--timeout $WAIT_TIMEOUT